service: moli-brms
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  architecture: x86_64
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  EventConsumer:
    handler: src/event-consumer.handler
    url: true
    events:
      - http:
          method: ANY
          path: /event/{path+}
